make:
	g++ main.cpp -o ./bin/FIST -Wall -Wconversion -Weffc++ -pedantic-errors -lsfml-window -lsfml-graphics -lsfml-system -std=c++20 -g

# -pedantic-errors is a no-compiler-extension flag for generating a standard behavior
# -lsfml-graphics -lsfml-window -lsfml-system is a SFML specifier flag
# -Wall -Wconversion -Weffc++ are for warning checking